### ISSUE TITLE
I can not Upload my Themes!

### ISSUE THREAD

**Issue by TTghostsemir** [ThemezerNX/Themezer#11]
Hello Everyone!
I have it on Discord Already reported! Discord ID is TT-ghost_semir#0280 ! 
My Problem is i can not Upload my Themes! On https://themezer.net/ ! I just get unknown error! Nobody on Discord could really help me also i hopp anyone can help me here! 

Thank you!

**Comment by Migushthe2nd** [comment]
Same people here, so you're out of luck 😶

**Comment by TTghostsemir** [comment]
Ah okay
