### ISSUE TITLE
[bug]没办法上传主题啊,咋整啊

### ISSUE THREAD

**Issue by tangyuxian** [ThemezerNX/Themezer#12]
如图所示,我上传主题后,给我显示**服务器问题**
![W0W6SE0Y9S{`69 AI){PA`H](https://user-images.githubusercontent.com/34386948/232772437-21e15660-82e7-44ba-8eec-e8f218e4bb97.png)
但是当我看这个界面,显示你们服务器没问题啊:
![MWOB~Y_ 5KC{$TPNQ0PMF{U](https://user-images.githubusercontent.com/34386948/232772650-dfc73bd4-5e7a-4740-9ff8-7e04d27107e9.png)
你说这是咋回事啊,就是你这个上传接口出错了:
![EY(X8X`JYRYR`JJAMD0(`~O](https://user-images.githubusercontent.com/34386948/232772724-2ab02844-ca8f-4783-bdd1-c20aa95ee73e.png)
我该咋整啊?

**Comment by Migushthe2nd** [comment]
Fixed!
