### ISSUE TITLE
can't change preview image

### ISSUE THREAD

**Issue by mc711** [ThemezerNX/Themezer#4]
i tried to change the preview image of my theme because i didn't have a good image at the time, but when i try to edit my theme and change the preview, it doesn't do anything after i select the new image...

**Comment by Migushthe2nd** [comment]
What is the url to your theme?

**Comment by mc711** [comment]
https://themezer.net/themes/playerselect/Black-2c4

**Comment by Migushthe2nd** [comment]
Cache seems to be the cause. Could you share the previous and the new image? The new images _are_ saved on the server, but some cache somewhere is causing the old image to display. This doesn't seem to be Cloudflare's cache.

**Comment by Migushthe2nd** [comment]
Were you able to save changes or does it not even let you do that at all?

**Comment by mc711** [comment]
it didn't allow me to save changes after i select the photo.

old - i just used a player select screenshot
![2020091816411700-CF99E5A89997DEB91E571D16DB468578](https://user-images.githubusercontent.com/2786469/94493035-f9585900-022e-11eb-9807-b2301d7e4d7c.jpg)

new - this is the user page now
![2020092621395700-CCFA659F4857F96DDA29AFEDB2E166E6](https://user-images.githubusercontent.com/2786469/94493039-feb5a380-022e-11eb-82f3-821f34c6680b.jpg)

**Comment by mc711** [comment]
im using firefox btw. i also disabled all adblock and content blockers. still not working.
