### ISSUE TITLE
New button for Switch Online

### ISSUE THREAD

**Issue by TristanVos** [ThemezerNX/Themezer#7]
So i updated my switch and it automaticly removed the theme, but now i have a new button "Switch Online" but that is not on the theme injector software yet :)
Just an suggestion of adding it

**Comment by Migushthe2nd** [comment]
Would you like to change the button's icon? That's not actually part of Themezer, but part of the SwitchThemeInjector. Check out [this issue](https://github.com/exelix11/SwitchThemeInjector/issues/73). Let me know if that's what you were referring to
