### ISSUE TITLE
Themezer.com - do we really lost our website? :( I see no page 

### ISSUE THREAD

**Issue by ssralpana** [ThemezerNX/Themezer#9]
I opened Themezer.com & even a lot of my friends complained that Themezer.com is offline & we see a sales page on the website.

It says Themezer.com is available for sale. 

What's happening?  please get back themezer.com

Thankyou.

**Comment by Migushthe2nd** [comment]
Hi,

The URL is actually https://themezer.net/, not `.com`. I don't plan on buying the `.com` domain, since it is quite expensive.

**Comment by ssralpana** [comment]
.net never feel secure to me 

did you change from themezer.com to themezer.net now?

**Comment by Migushthe2nd** [comment]
It has always been `.net`. The TLD has nothing to do with security. `.net` domains are a bit cheaper though, so I guess it could be that that more "bad" websites use the `.net` TLD.

**Comment by ssralpana** [comment]
I still fear to download something from a themezer.net i had a very bad experience something downloaded from a .net website and my friend even says the same

**Comment by ssralpana** [comment]
If it's really very expensive to buy a .com I could help donating some money for the good will. let me know how much @Migushthe2nd

**Comment by Migushthe2nd** [comment]
Sorry, but `.net` is a completely normal suffix (fifth popular one actually). I don't plan on changing to `.com`, because it basically doesn't change anything and costs €100 to claim the domain + would induce yearly costs to keep the domain. It would also cause confusion to the users.

**Comment by ssralpana** [comment]
no confusion but a more trust from the people like us, i wanted to use themes but scared to get from a .net website which we don't usually trust/ 

100€ and i could help you 1/2 in the contribution.

**Comment by Migushthe2nd** [comment]
I appreciate the offer, but I'm not going to switch domains. Sorry

**Comment by HarishMelwani** [comment]
On searching **Themezer**, I've landed here...Thankyou @ssralpana for recommending @Migushthe2nd to use the universal .com version of the domain name which 99% of the people are aware of... @Migushthe2nd you don't need to change your whole domain name now...you can just redirect the .com version to the .net one which you use for the website. 

The process is simple & Yeah, I'm the owner of the domain name recommending you here to acquire it :) !! 

The domain is quite good for your expansion, establishing authority and online presence in the area of your work. It is easy to remember and easy for your users to type into their web browser.

Could be the great sort of execution online, that could help you grow authority & much leads / visitors to your business.

The domain has been hitting a 100's of visitors everyday & I think this could be a great opportunity for you to acquire it at the moment, Increase traffic & Make more leads to your business.


Atleast, this could help people who're confused like @ssralpana to land at your place in a click.

**Comment by Migushthe2nd** [comment]
@HarishMelwani ![booty-among-us.gif](https://user-images.githubusercontent.com/22274715/161639112-5a894fd0-94a6-4196-aec3-17fe149afded.gif)

**Comment by HarishMelwani** [comment]
@Migushthe2nd hahaa!! I swear not at the much price. You'll love to hear it.

**Comment by HarishMelwani** [comment]
![image](https://user-images.githubusercontent.com/26843056/161639634-b6394d12-ff68-450b-afb5-045b76d33394.png)

**Comment by Migushthe2nd** [comment]
I really don't care, goodbye!
